/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: "class",
  content: ["./src/**/*.{js,jsx,ts,tsx}"],
  theme: {
    extend: {
      colors: {
        "surface-container-highest": "#262626",
        /* Was #adaaaa — lifted for WCAG-friendly body/secondary text on #0e0e0e */
        "on-surface-variant": "#c9c7c5",
        "primary-fixed-dim": "#00deec",
        "outline-variant": "#5c5a58",
        primary: "#8ff5ff",
        tertiary: "#ac89ff",
        "tertiary-dim": "#874cff",
        "surface-bright": "#2c2c2c",
        "on-primary-fixed-variant": "#005e64",
        "tertiary-fixed": "#bda1ff",
        "primary-container": "#00eefc",
        "surface-container-lowest": "#000000",
        "secondary-container": "#9900cf",
        surface: "#0e0e0e",
        "on-tertiary-container": "#f8f1ff",
        "surface-variant": "#262626",
        "inverse-on-surface": "#6e6c6a",
        "on-primary-fixed": "#003f43",
        "error-dim": "#d7383b",
        "secondary-fixed": "#f1c1ff",
        background: "#0e0e0e",
        "on-tertiary": "#290067",
        "tertiary-fixed-dim": "#b190ff",
        "primary-dim": "#00deec",
        "on-secondary-fixed-variant": "#8400b3",
        "secondary-dim": "#bb00fc",
        "on-error": "#490006",
        secondary: "#d674ff",
        "secondary-fixed-dim": "#eaaeff",
        "surface-container-high": "#201f1f",
        outline: "#777575",
        "on-primary-container": "#005359",
        "on-tertiary-fixed-variant": "#4700a7",
        error: "#ff716c",
        "on-primary": "#005d63",
        "surface-container": "#1a1919",
        "on-secondary-container": "#fff5fc",
        "on-error-container": "#ffa8a3",
        "tertiary-container": "#7000ff",
        "surface-tint": "#8ff5ff",
        "inverse-primary": "#006a71",
        "on-tertiary-fixed": "#1f0052",
        "error-container": "#9f0519",
        "on-secondary": "#390050",
        "primary-fixed": "#00eefc",
        "on-surface": "#ffffff",
        "on-background": "#ffffff",
        "surface-container-low": "#131313",
        "inverse-surface": "#fcf8f8",
        "surface-dim": "#0e0e0e",
        "on-secondary-fixed": "#580079",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      fontFamily: {
        headline: ["Space Grotesk", "system-ui", "sans-serif"],
        body: ["Inter", "system-ui", "sans-serif"],
        label: ["Space Grotesk", "system-ui", "sans-serif"],
      },
    },
  },
  plugins: [],
};
